title: Lotech DevOps
description: Blog sobre DevOps, Cloud e Automação.
Compartilho experiências, tutoriais e boas práticas sobre Linux, Kubernetes, Terraform, Ansible e AWS.
author: Neto
email: divinoneto@gmail.com
theme: jekyll-theme-hacker